/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData human = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marvel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData universe = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData villain = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData age = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alien = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antihero = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData height = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hero = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
